env: "local" # local, dev, prod

http_server:
  address: "localhost:8082"
  timeout: 4s # Timeout requests
  idle_timeout: 60s # Timeout for connections

storage:
  driver: "mysql"
  connection:
    username: "root"
    password: "9Ba626ab3c@"
    host: "172.17.0.1"
    port: 3307
    database: "userroles"
    params:
      charset: "utf8mb4"
      parseTime: "True"
      loc: "Local"